server:
  port: 5001

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5434}/${DB_NAME:customer_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: liquibase/main.xml
    enabled: true

kafka:
  consumer:
    active-orders-count:
      bootstrap-servers: ${KAFKA_IP:localhost}:${KAFKA_PORT:5092}
      topic: active-orders-count
      group-id: customer-service-gr1
      username: ${KAFKA_USERNAME:espiel_customer_service}
      password: ${KAFKA_PASSWORD:customer_service_psw}