server:
  port: 5002

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5435}/${DB_NAME:order_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: liquibase/main.xml
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_IP:localhost}:${KAFKA_PORT:5092}
    username: ${KAFKA_USERNAME:espiel_order_service}
    password: ${KAFKA_PASSWORD:order_service_psw}
    admin:
      properties:
        security:
          protocol: SASL_PLAINTEXT
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${spring.kafka.username}" password="${spring.kafka.password}";

kafka:
  producer:
    active-orders-count:
      bootstrap-servers: ${KAFKA_IP:localhost}:${KAFKA_PORT:5092}
      topic: active-orders-count
      username: ${KAFKA_USERNAME:espiel_order_service}
      password: ${KAFKA_PASSWORD:order_service_psw}