server:
  port: 5002

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5435}/${DB_NAME:order_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: liquibase/main.xml
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_IP:localhost}:${KAFKA_PORT:5092}

kafka:
  producer:
    active-orders-count:
      bootstrap-servers: ${KAFKA_IP:localhost}:${KAFKA_PORT:5092}
      topic: active-orders-count
      replies-topic: active-orders-count-replies
      replies-group-id: order-service-gr1
      replies-timeout-days: 1